#!/bin/bash
cd `dirname $0`
set -e

BUILD_DIR=$PWD
REDIS_VERSION=${1:-2.8.3}
REDIS_TAR=redis-$REDIS_VERSION.tar.gz
REDIS_DIR=$BUILD_DIR/redis-$REDIS_VERSION
ROOTFS=$BUILD_DIR/rootfs-redis-server
export DEBIAN_FRONTEND=noninteractive

### Build redis ###

rm -rf $REDIS_DIR

apt-get install -y wget build-essential
wget -c http://download.redis.io/releases/$REDIS_TAR
tar xzvf $REDIS_TAR
cd $REDIS_DIR
make CFLAGS=--static

## Create image

rm -rf $ROOTFS

mkdir $ROOTFS
cd $ROOTFS

mkdir bin etc dev dev/pts lib proc sys tmp
touch etc/resolv.conf
cp /etc/nsswitch.conf etc/nsswitch.conf
echo root:x:0:0:root:/:/bin/sh > etc/passwd
echo root:x:0: > etc/group
ln -s lib lib64
ln -s bin sbin
for X in console null ptmx random stdin stdout stderr tty urandom zero
do
  cp -a /dev/$X dev
done

## Install redis and dependencies
cp /lib/x86_64-linux-gnu/lib{pthread,c,dl,nsl,nss_*}.so.* lib
cp /lib/x86_64-linux-gnu/ld-linux-x86-64.so.2 lib
cp /lib/x86_64-linux-gnu/libm.so.6 lib

# TODO: Also add the sentinel ?
cp $REDIS_DIR/src/redis-server bin/redis-server
ln -s redis-server bin/init

## Export to docker
tar --numeric-owner -cf- . | docker import - zimbatm/redis-server-base
